
// /**
//  * 2024-11-04:  Copied from PhotoFormWebpart
//  * Sample functions generated by ChatGPT for handling various types of file.
//  *  2024-11-03:  Currently tested and used in PasteFormForm.tsx in PhotoForm.
//  *
//  */

// // eslint-disable-next-line @rushstack/no-new-null
// export function handleImagePaste (e: ClipboardEvent, setImageData: (data: string | null) => void ): void {
//   // Get the clipboard items from the event
//   const clipboardItems = e.clipboardData?.items;

//   // Loop through each item in the clipboard
//   if ( clipboardItems ) for (let i = 0; i < clipboardItems?.length; i++) {
//     // Check if the item is an image
//     if (clipboardItems[i].type.indexOf('image') !== -1) {
//       // Get the image file from the clipboard item
//       const file = clipboardItems[i].getAsFile();

//       // Create a new FileReader instance
//       const reader = new FileReader();

//       // Define what to do when the file has been read
//       reader.onloadend = function () {
//         // Store the base64 image data
//         setImageData(reader.result as string);
//       };

//       // Start reading the image file as a Data URL (base64 format)
//       reader.readAsDataURL(file as Blob);
//     }
//   }
// }